### ISSUE TITLE
Newlines not preserved in some circumstances (lists?)

### ISSUE THREAD

**Issue by Skirmisher** [dariusk/rss-to-activitypub#13]
I've observed some discrepancies in the server's formatting of new RSS entries vs. what appears in an RSS reader. Namely, the text preview lacks newlines where they exist in the original text. I think this may only occur with lists, but I don't have other feeds' outputs on hand to verify.

The view of a particular article in my RSS reader: 

![A screenshot of a Seattle Transit Blog article titled "News Roundup: Long Distance", featuring a picture of an Amtrak train, followed by a bulleted list of news headlines](https://user-images.githubusercontent.com/1535247/53284532-a4776700-370a-11e9-9f8e-21add2d69554.png)

The corresponding output from the server:

![The same article entry as published by the server, with the bulleted list collapsed into one large, unreadable paragraph](https://user-images.githubusercontent.com/1535247/53284536-b9ec9100-370a-11e9-9c6a-2a8412cccba8.png)

**Comment by dariusk** [comment]
The issue is that your server is stripping the formatting out of the post. `<ul><li>` etc aren't allowed markup on many ActivityPub servers; certainly not on regular Mastodon. (I am not sure what system you are on.)

Eventually I would like more of these services to fully support messages coming in tagged as an `Article` in ActivityPub. The idea is that if Mastodon (for example) sees an `Article` come in (instead of a `Note`, which it currently converts things to), it would render it as full text article with at least minimum html formatting.

I originally had some rules that would turn bullet points into text bullets so they would come in like

```
- one
- two
-three
```

But the problem with that is false positives. It basically messes up a lot of the time. What we really need is full `Article` support.
