### ISSUE TITLE
Content is getting duplicated for some feeds

### ISSUE THREAD

**Issue by tachyons** [dariusk/rss-to-activitypub#9]
I created this account, and it is now posting same content again and again. 2.1k posts within few hours 
 https://bots.tinysubversions.com/u/oneindia

**Comment by dariusk** [comment]
Thank you, I will take a look!

**Comment by dariusk** [comment]
It seems like it's a problem with their RSS feed: it seems to be posting many dozens or hundreds of posts an hour. This might be "correct" (it's hard for me to tell because I can't read Malayalam) if it's for example, posting every single update to a busy website. Or it might be "incorrect" if they are doing things like reposting the same article with a different date every few minutes due to a bug. Regardless, it seems like a broken/useless RSS feed. Sorry about that, there really isn't anything I can do.

**Comment by tachyons** [comment]
Got it, basically they are repeating same story. Probably with different timestamp.
